controllers:
    resource:
        path: ../src/Controller/
        namespace: Acme\CountUp\Controller
    type: attribute

api_challenge_new:
    path: /api/challenge/new
    controller: Acme\CountUp\Controller\GameController::newChallenge
    methods: [GET]

api_challenge_get:
    path: /api/challenge
    controller: Acme\CountUp\Controller\GameController::getChallenge
    methods: [GET]

api_challenge_submit:
    path: /api/challenge
    controller: Acme\CountUp\Controller\GameController::submitChallenge
    methods: [POST]

api_challenge_complete:
    path: /api/challenge/complete
    controller: Acme\CountUp\Controller\GameController::completeChallenge
    methods: [POST]