FROM php:8.4-fpm-alpine
WORKDIR /var/www/countup

COPY . .

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN docker-php-ext-install pdo pdo_mysql

# Xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN apk update && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
    && pecl install xdebug-3.4.4 \
    && docker-php-ext-enable xdebug \
    && apk del -f .build-deps
# Override the value from the ini when inside docker - Required for Xdebug to communicate with us outside the container.
ENV XDEBUG_CONFIG="client_host=host.docker.internal"

# Install and init Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENTRYPOINT [ "/bin/sh", "container-entrypoint.sh" ]